version: '3.8'

services:
  web:
    build:
      context: .
    container_name: django_app
    command: 
      - /bin/sh
      - '-c'
      - '/app/scripts/init.sh'
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .dockerenv
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: