# Generated by Django 5.1.6 on 2025-03-03 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('validator', 'Valid'), ('norole', 'Norole')], default='norole', max_length=9),
        ),
    ]
