# Generated by Django 5.1.6 on 2025-03-05 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('validator', 'Valid'), ('visitor', 'Visitor')], default='visitor', max_length=9),
        ),
    ]
