# Generated by Django 5.1.6 on 2025-03-07 11:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('type', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('keywords', models.JSONField(blank=True, null=True)),
                ('chrono', models.JSONField(blank=True, null=True)),
                ('location', models.JSONField(blank=True, null=True)),
                ('location_name', models.CharField(blank=True, max_length=150, null=True)),
                ('geology', models.CharField(blank=True, max_length=150, null=True)),
                ('geo_description', models.TextField(blank=True, null=True)),
                ('historio', models.TextField(blank=True, null=True)),
                ('justification', models.TextField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
