# Generated by Django 5.1.6 on 2025-04-04 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0003_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='resources/'),
        ),
        migrations.AddField(
            model_name='site',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='resources/'),
        ),
        migrations.AddField(
            model_name='subsite',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='resources/'),
        ),
    ]
