# Generated by Django 5.1.6 on 2025-04-04 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0005_mission'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='missions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='entities.mission'),
        ),
    ]
