# Generated by Django 5.1.6 on 2025-04-04 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0006_site_missions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='missions',
        ),
        migrations.AddField(
            model_name='site',
            name='missions',
            field=models.ManyToManyField(blank=True, to='entities.mission'),
        ),
    ]
