name: Deploy to O2switch

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      force_deploy:
        description: 'Force deployment even without changes'
        required: false
        default: false
        type: boolean

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install Node dependencies
      run: npm install
      
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
        # Installer Django moderne avec Python 3.12
        pip install --target ./vendor django psycopg2-binary python-dotenv
        
    - name: Build SCSS assets
      run: npm run build
      
    - name: Collect static files
      run: |
        python manage.py collectstatic --noinput
        
    - name: Create deployment package
      run: |
        # Créer un dossier temporaire pour les fichiers à déployer
        mkdir -p deploy-package
        
        # Copier les fichiers Python/Django
        cp -r authentication/ deploy-package/
        cp -r client/ deploy-package/
        cp -r entities/ deploy-package/
        cp -r failaka/ deploy-package/
        
        # Copier resources s'il contient des fichiers
        if [ "$(ls -A resources/ 2>/dev/null)" ]; then
          cp -r resources/ deploy-package/
        fi
        cp -r templates/ deploy-package/ 2>/dev/null || echo "ℹ️ Pas de dossier templates/"
        
        # Copier les fichiers de configuration
        cp manage.py deploy-package/
        cp requirements.txt deploy-package/
        cp .htaccess deploy-package/
        
        # Copier les dépendances Python embarquées
        if [ -d "./vendor" ]; then
          cp -r vendor/ deploy-package/
        fi
        
        # Copier le script CGI pour O2switch
        cp -r cgi-bin/ deploy-package/
                
        # Copier SEULEMENT les assets buildés (pas les sources ni node_modules)
        mkdir -p deploy-package/static/
        cp -r static/* deploy-package/static/ 2>/dev/null || echo "⚠️ No files in static/"
        
        # Créer un fichier de version
        echo "$(date '+%Y-%m-%d %H:%M:%S') - $(git rev-parse --short HEAD)" > deploy-package/version.txt
        
    - name: Deploy to O2switch via SFTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.O2SWITCH_SFTP_HOST }}
        username: ${{ secrets.O2SWITCH_SFTP_USERNAME }}
        password: ${{ secrets.O2SWITCH_SFTP_PASSWORD }}
        port: ${{ secrets.O2SWITCH_SFTP_PORT || 21 }}
        protocol: ftp
        local-dir: ./deploy-package/
        server-dir: ./
        exclude: |
          **/.git*
          **/.git*/**
          **/__pycache__/**
          **/*.pyc
          **/.env*
          **/env/**
          **/venv/**
          **/.DS_Store
          **/Thumbs.db
          **/tests/**
          **/*.test.js
          **/*.test.py
          
    - name: Cleanup
      run: rm -rf deploy-package
      
    - name: Deployment notification
      if: success()
      run: |
        echo "✅ Déploiement réussi"
        echo "📅 Date: $(date)"
        echo "🔖 Commit: $(git rev-parse --short HEAD)"
        echo "📝 Message: $(git log -1 --pretty=%B)"